### PR TITLE
Added option to filter against localStorageKeys array in props

### PR DESCRIPTION
**Pull request by shantp**
Needed to only save parts of a component's state to localStorage so created this extra option to check against an array of keys stored in defaultProps under 'localStorageKeys'

### CODE REVIEW

**Comment by STRML** [comment]
Decent addition. A few things I'd like to see added before merging:

* Please rename the prop to something more obvious (like `stateFilterKeys`)
* Add the function `getStateFilterKeys` so this can be defined on the component itself
* Document this in the README
* Squash commits

Thanks!

**Comment by shantp** [comment]
Updated and squashed.

**Comment by shantp** [comment]
Could you merge this if it looks good and publish a new version? I'm trying to use this in production at work. Sorry to bug if you're busy.

**Comment by STRML** [comment]
Thanks for the PR and sorry it took so long to merge. This is in `0.2.5`.

**Pull request merged**
