### PR TITLE
Address unhandled exception in Safari private mode

### LINKED ISSUE #3: DOM Exception 18 on iOS when cookies are disabled.
Just by accessing `localStorage` [here on this line](https://github.com/STRML/react-localstorage/blob/master/react-localstorage.js#L4), it will cause iOS Safari to throw the above exception. Which can cause the entire react app to crash.

There is a fix though, take a look at how modernizr or [angular does it](https://github.com/angular-translate/angular-translate/commit/75504cbe2ddc0d18e08288b0fa4453356aaafe73).

### PR DESCRIPTION
**Pull request by hongymagic**
This fixes #3. Currently missing tests mainly due to the fact I have no idea (and could not find docco) on how to setup karma environment such that localStorage is missing and/or throws exceptions.

- [ ] Write a test case to cater for missing localStorage
- [ ] Write a test case to cater for localStorage throwing exceptions

Any ideas?

### CODE REVIEW

**Comment by hongymagic** [comment]
Managed to find a way to configure custom launcher, Chrome with custom argument: `--disable-local-storage` which seems to behave slight different to above logic. When Chrome is run with the above argument:

* `'localStorage' in global; // true`
* `global.localStorage` === null; // true`

I will change the logic and add tests to cater for these conditions as well.

**Comment by STRML** [comment]
Very nicely done. Thanks for the contribution!

**Comment by STRML** [comment]
This is in `0.2.3`.

**Comment by STRML** [comment]
Please open another PR for the tests. I wanted to get the change in ASAP to ensure this stops breaking the user experience on iOS.

**Pull request merged**
